language: ruby
cache: bundler

rvm:
- 2.7
- 3.0
- 3.1
- 3.2

notifications:
  email: false

jobs:
  fast_finish: true

before_install:
  - sudo apt-get update
  - sudo apt-get install python
  - nvm install --lts
  - nvm use node
  - gem install bundler -v 2.4.22


install:
  - pip install --user bumpversion
  - npm install -g semantic-release
  - npm install -g @semantic-release/exec
  - npm install -g @semantic-release/git
  - npm install @semantic-release/github
  - npm install -g @semantic-release/commit-analyzer
  - bundle install

script:
- bundle exec rake

deploy:
 - provider: script
   script: npx semantic-release
   on:
     branch: master
     rvm: 2.7

 - provider: rubygems
   api_key: $RUBYGEMS_API_KEY
   gem: ibm_vpc
   on:
     rvm: 2.7
     branch: master